title: Lockbox
author: Mozilla
email: lockbox-dev@mozilla.com
github_username: mozilla-lockbox

theme: minima

plugins:
  - jekyll-seo-tag

header_pages:
  - process.md
  - architecture/index.md

include: [".well-known"]
