title: Firefox Lockbox
author: Mozilla
email: lockbox-contact@mozilla.com
github_username: mozilla-lockbox

theme: minima

plugins:
  - jekyll-seo-tag

header_pages:
  - faq.md
  - privacy.md
  - process.md
  - architecture/index.md

include: [".well-known"]
