title: Firefox Lockbox
author: Mozilla
email: lockbox-contact@mozilla.com
github_username: mozilla-lockbox
android_link: https://app.adjust.com/eu4xdqg?redirect=https://play.google.com/store/apps/details?id=mozilla.lockbox
ios_link: https://app.adjust.com/eu4xdqg?redirect=https://itunes.apple.com/us/app/firefox-lockbox/id1314000270?mt=8

theme: minima

plugins:
  - jekyll-seo-tag

header_pages:
  - faq.md
  - privacy.md

footer_pages:
- faq.md
- privacy.md

include: [".well-known"]
